repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.38.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@^8.0.1
          - eslint-config-standard-with-typescript@latest
          - eslint-plugin-import@^2.25.2
          - eslint-plugin-n@^15.0.0
          - eslint-plugin-promise@^6.0.0
          - "@typescript-eslint/eslint-plugin@^5.43.0"
