preset: angular
branches:
  - vanilla
  - react
  - vue
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
